name: Unit-Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GOU_TEST_AES_KEY: "^*aNBue!loLTTiP*4i&BSK7s#QRbe0^g"
  GOU_TEST_REDIS_HOST: "127.0.0.1"
  GOU_TEST_REDIS_PORT: "6379"
  GOU_TEST_GITHUB_TOKEN: ${{ secrets.GOU_TEST_GITHUB_TOKEN }}
  GOU_TEST_GITHUB_REPO: github.com/YaoApp/workshop-tests-private
  GOU_TEST_DSL_TABLE_NAME: test_env
  SEND_MAIL_WORKER_NUMS: 2
  SEND_MAIL_TEST_MAIL: max@iqka.com

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.18.2]
        db: [MySQL8.0, SQLite3]
        redis: [4, 5, 6]
    steps:
      - name: Checkout Kun
        uses: actions/checkout@v2
        with:
          repository: yaoapp/kun
          path: kun

      - name: Checkout Xun
        uses: actions/checkout@v2
        with:
          repository: yaoapp/xun
          path: xun

      - name: Checkout V8Go
        uses: actions/checkout@v2
        with:
          repository: rogchap/v8go
          ref: 5e91d3d9dcabd2986f901b6b31590e49fc3c4dd8
          path: v8go

      - name: Checkout Demo WMS
        uses: actions/checkout@v2
        with:
          repository: yaoapp/demo-wms
          path: demo-wms

      - name: Move Kun, Xun, V8go
        run: |
          mv kun ../
          mv xun ../
          mv v8go ../
          mv demo-wms ../
          ls -l .
          ls -l ../

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis }}

      - name: Setup ${{ matrix.db }}
        uses: ./.github/actions/setup-db
        with:
          kind: "${{ matrix.db }}"
          db: "gou"
          user: "gou"
          password: "123456"

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Setup Go Tools
        run: |
          make tools

      - name: Setup ENV
        run: |
          echo "GOU_TEST_DSN=$DSN" >> $GITHUB_ENV
          echo "GOU_TEST_DB_DRIVER=$DB_DRIVER" >> $GITHUB_ENV
          echo "GOU_TEST_API_ROOT=$GITHUB_WORKSPACE/app/apis" >> $GITHUB_ENV
          echo "GOU_TEST_FLW_ROOT=$GITHUB_WORKSPACE/app/flows" >> $GITHUB_ENV
          echo "GOU_TEST_MOD_ROOT=$GITHUB_WORKSPACE/app/models" >> $GITHUB_ENV
          echo "GOU_TEST_PLG_ROOT=$HOME/data/gou-unit/plugins" >> $GITHUB_ENV
          echo "GOU_TEST_SCRIPT_ROOT=$GITHUB_WORKSPACE/app/scripts" >> $GITHUB_ENV
          echo "GOU_TEST_QUERY_ROOT=$GITHUB_WORKSPACE/query/assets" >> $GITHUB_ENV
          echo "GOU_TEST_PLG_LOG=$HOME/data/gou-unit/logs" >> $GITHUB_ENV
          echo "GOU_TEST_APP_ROOT=$GITHUB_WORKSPACE/tests/app" >> $GITHUB_ENV
          echo "YAO_PATH=$GITHUB_WORKSPACE/tests/yao" >> $GITHUB_ENV
          mkdir -p $HOME/.yao
          echo ${{ secrets.GOU_TEST_GITHUB_TOKEN }} > $HOME/.yao/github_token
          chmod 600 $HOME/.yao/github_token
          ls -l $HOME/.yao/github_token

      - name: Run Test
        run: |
          make vet
          make fmt-check
          make misspell-check
          make plugin
          make migrate
          make test

      - name: Codecov Report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
